### ISSUE TITLE
Issue when calling command "dialectMorph"

### ISSUE THREAD

**Issue by brokoli777** [Kannav02/DialectMorph#2]
![Screenshot 2024-09-12 at 3 10 43 PM](https://github.com/user-attachments/assets/683bb8c9-420d-4242-bb98-8b87deadac40)

When calling dialectMorph, the application doesn't seem to run but when I directly run index.ts, the application run properly.

![Screenshot 2024-09-12 at 3 12 21 PM](https://github.com/user-attachments/assets/6df1e577-100d-4d81-99e6-df8cd4e36d52)

**Comment by brokoli777** [comment]
I believe it is related to this [issue](https://github.com/Kannav02/DialectMorph/issues/1)

**Comment by Kannav02** [comment]
Thank you for raising this issue , I replicated the same issue on a VM as can be seen in the image below

Image 1
![Screenshot 2024-09-12 at 5 13 00 PM](https://github.com/user-attachments/assets/06c17f15-9f9b-4347-86f9-2f929154466d)

on replicating I found that the issue was arising because I hadn't given the instruction to build the file before running bun link

so to make the binary runnable , try to run the following command before using any of the ``` link ``` scripts


```
bun run build
```

the PR #5 closes this issue , thank you for pointing this issue out
